import "../globals.css";
import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import { Header } from "@/modules/Header/Header";
import { ReactQueryProvider } from "../ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ weight: "300", subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ReactQueryProvider>
          <Header />
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
